### PR TITLE
Create maven.yml

### PR DESCRIPTION
**Pull request by Sahejpalarneja**
Lets see if this works

### CODE REVIEW

**Comment by Sahejpalarneja** [comment]
Do not merge yet

**Comment by yves1706** [comment]
I thought I fixed the Asteroid test problem with the commit 4e5a0ca9b433410effee9c306ee8516101e931e6
The tests work locally but automation still fails.

**Comment by yves1706** [comment]
I disabled the failed tests in the last commit 90cad15
I suggest that we proceed without them for now. 
@Sahejpalarneja Do you agree?

**Comment by Sahejpalarneja** [comment]
> 

We can move forward with merge and fix test later . Created issue #49

**Pull request merged**
